Improve logging & possibly fix issues w/ Node.js 17+
chrisguttandin/dynamo-db-local pull request #112
Opened 2022-12-17 08:12 UTC by o-alexandrov

DynamoDB doesn't spin up for me w/ Node.js 17+, unless `stdio: 'inherit'` is set.

But, primarily, this PR should improve logging of what is being spawned.
Users should start seeing similar to the following in their CLI:

<img width="449" alt="Screenshot 2022-12-17 at 2 11 50 AM" src="https://user-images.githubusercontent.com/9992724/208232564-8bb63abf-0d0b-4c2d-8996-c08b92743204.png">

2022-12-21 09:03 UTC, chrisguttandin requested changes
Thanks a lot for fixing/adding this. Could you please remove the comment before the merge?

2022-12-21 09:03 UTC, chrisguttandin commented on src/module.js
> +        stdio: 'inherit' // use parent's: "stdin", "stdout", "stderr" streams for better logging
```suggestion
        stdio: 'inherit'
```

2022-12-21 15:59 UTC, merged

2023-01-03 07:41 UTC, o-alexandrov commented
@chrisguttandin thank you for merging this and kindly adjusting the tests in d6fb0e6b163059a1a01d5d627828dfb488eb1e1f.
I apologize for disturbing you, could you please let me know when do you plan to publish the change?
- this minuscule change really does fix initialization issues on node.js 17+

2023-01-03 09:14 UTC, chrisguttandin commented
Hi @o-alexandrov, sorry for the delay.

I usually use a bot to publish new versions. It was already configured to drop support for Node.js v12 which means it would publish a major version since that's possibly a breaking change. I didn't want that to happen while everyone is on holidays and that's why I paused it for now.

Long story short, I just published v4.2.0 which contains your changes. Thanks again for your contribution. Likely there will be a v5 release later this week which drops support for Node.js v12.

2023-01-03 13:18 UTC, chrisguttandin commented
Hi @o-alexandrov, I realized the hard way that this was a breaking change. I therefore pushed another change which sets `stdio` to `'pipe'` which is the default value. But it is possible to override this by providing a different value. I hope this works for you, too.

https://github.com/chrisguttandin/dynamo-db-local/commit/a4e0a92b8258952656d51ac302f54d6db61064fb

2023-01-03 13:21 UTC, o-alexandrov commented
Yes, nice, thank you for letting to override and thoughtfully keeping the default behavior.
Apologies for introducing a breaking change, I didn't expect that

2023-01-03 15:19 UTC, chrisguttandin commented
No worries, I didn't see this coming, too.